/*
 * OSCam WebIf Wiki data - AUTO GENERATED, DO NOT EDIT!
 * Generated by wiki_gen from wiki markdown files
 */
#ifndef WEBIF_PAGES_WIKI_H_
#define WEBIF_PAGES_WIKI_H_

#ifdef WEBIF_WIKI

#define COMPRESSED_WIKI 1

struct wiki_entry {
	uint32_t param_ofs;
	uint32_t config_ofs;
	uint32_t section_ofs;
	uint32_t text_ofs;
	int8_t status;
};

int32_t wiki_count(void);
const struct wiki_entry *wiki_get_entries(void);
const char *wiki_get_help(const char *config, const char *section, const char *param);
int8_t wiki_get_status(const char *config, const char *section, const char *param);
void wiki_get_data(const char **data, size_t *data_len, size_t *data_olen);
char *wiki_get_decompressed_data(void);
void webif_wiki_prepare(void);
void webif_wiki_free(void);

#endif /* WEBIF_WIKI */

#endif /* WEBIF_PAGES_WIKI_H_ */
